[versions]
agp = "8.10.1"
kotlin = "2.0.21"
napier = "2.7.1"
spotless = "7.0.4"
dokka = "1.9.20"
kotlinStdlib = "2.0.21"
keypleInteropJsonapiClientKmpLib = "0.1.6"
keypleInteropLocalreaderNfcmobileKmpLib = "0.1.6"

[libraries]
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
keypleInteropJsonapiClientKmpLib = { module = "org.eclipse.keyple:keyple-interop-jsonapi-client-kmp-lib", version.ref = "keypleInteropJsonapiClientKmpLib" }
keypleInteropLocalreaderNfcmobileKmpLib = { module = "org.eclipse.keyple:keyple-interop-localreader-nfcmobile-kmp-lib", version.ref = "keypleInteropLocalreaderNfcmobileKmpLib" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
